# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:33
from __future__ import unicode_literals

import classroom_analyst.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_img', models.ImageField(blank=True, default='/classroom_analyst/static/img/dummy.png', null=True, upload_to=classroom_analyst.models.upload_in_profiles)),
                ('about_me', models.CharField(blank=True, max_length=150, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('positive_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('neutral_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('negative_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
