# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:45
from __future__ import unicode_literals

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_img',
            field=models.ImageField(null=True, upload_to=attendance.models.upload_in_profiles),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
